version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: messenger_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_CONNECTION_STRING: "dbname=messenger_db user=admin password=root host=db"
    command: bash -c "sleep 30 && /app/bin/db_manager"
